name: Build For Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
      
    - name: Build Debug
      run: dotnet build --self-contained

    - name: Build Release
      run: dotnet build --configuration Release --self-contained
      
    - name: Upload Debug Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Debug
        path: |
          bin/Debug/net8.0/win-x64

    - name: Upload Release Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Debug
        path: |
          bin/Release/net8.0/win-x64
