name: Build For Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Test
      run: dotnet publish win-x64
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build Debug
      run: dotnet build --no-restore --self-contained true

    - name: Build Release
      run: dotnet build --configuration Release --no-restore --self-contained true
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Debug
        path: |
          bin/Debug/net8.0/Nova.exe
          bin/Debug/net8.0/Nova.dll

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Release
        path: |
          bin/Release/net8.0/Nova.exe
          bin/Release/net8.0/Nova.dll
